### ISSUE TITLE
🔁 Upgrade to Solidity Version `0.8.22`

### ISSUE THREAD

**Issue by pcaversaccio** [pcaversaccio/createx#20]
- Official Release: https://github.com/ethereum/solidity/releases/tag/v0.8.22.
- We should use the feature that you can now access events from other contracts for our Foundry tests.

**Comment by pcaversaccio** [comment]
@mds1 do you agree with this upgrade as well? It will also help to refactor some of the redundant event definitions in the Foundry tests due to the [ICE](https://github.com/ethereum/solidity/issues/14430) of Solidity Version `0.8.21`.

**Comment by mds1** [comment]
In general I'm ok with upgrading. My only suggestion is we might want to wait a few weeks before deploying for production if we're using a brand new solc version, since in the past there's occasionally been small bugs found after new releases, so waiting just gives some extra confidence around we're not subject to one of them

**Comment by pcaversaccio** [comment]
Yeah, I fully agree on waiting a few weeks.
